### ISSUE TITLE
As a Catosplace Engineer, I expect this role to manage its GitHub Action version securely using best practice

### ISSUE THREAD

**Issue by petersellars** [catosplace/ansible-engineering-base-role#7]
To enable Dependabot, create a file called .github/dependabot.yaml:

```
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
```
